/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a booking for an available slot */
        post: operations["Guest_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List active event types only */
        get: operations["Guest_listActiveEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type (only if active) */
        get: operations["Guest_getActiveEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get available time slots for the next 14 days */
        get: operations["Guest_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/blackouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all blackout periods */
        get: operations["Owner_listBlackouts"];
        put?: never;
        /** @description Create a blackout period */
        post: operations["Owner_createBlackout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/blackouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a blackout period */
        delete: operations["Owner_deleteBlackout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List bookings (paginated, filterable) */
        get: operations["Owner_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types (including inactive) */
        get: operations["Owner_listEventTypes"];
        put?: never;
        /** @description Create a new event type */
        post: operations["Owner_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type by ID */
        get: operations["Owner_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Partially update an event type */
        patch: operations["Owner_updateEventType"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns OK if the service is running */
        get: operations["Health_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One-off time range that prevents new bookings */
        Blackout: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /**
             * Format: date-time
             * @description Start of blackout period (ISO 8601, UTC)
             */
            startTime: string;
            /**
             * Format: date-time
             * @description End of blackout period (ISO 8601, UTC)
             */
            endTime: string;
            /** @description Optional reason for the blackout */
            reason?: string;
            /**
             * Format: date-time
             * @description Creation timestamp (ISO 8601, UTC)
             */
            createdAt: string;
        };
        /** @description Full booking resource returned to the owner */
        Booking: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /**
             * Format: uuid
             * @description ID of the associated event type
             */
            eventTypeId: string;
            /** @description Snapshot of event type name at booking time */
            eventTypeName: string;
            /** @description Guest's display name */
            guestName: string;
            /** @description Optional notes from the guest */
            notes?: string;
            /**
             * Format: date-time
             * @description Start time (ISO 8601, UTC)
             */
            startTime: string;
            /**
             * Format: date-time
             * @description End time (ISO 8601, UTC) — derived from startTime + 30 minutes
             */
            endTime: string;
            /**
             * Format: date-time
             * @description Creation timestamp (ISO 8601, UTC)
             */
            createdAt: string;
        };
        /** @description Payload to create a blackout period */
        CreateBlackoutRequest: {
            /**
             * Format: date-time
             * @description Start of blackout period (ISO 8601, UTC)
             */
            startTime: string;
            /**
             * Format: date-time
             * @description End of blackout period (ISO 8601, UTC) — must be after startTime
             */
            endTime: string;
            /** @description Optional reason */
            reason?: string;
        };
        /** @description Payload to create a new booking */
        CreateBookingRequest: {
            /**
             * Format: uuid
             * @description ID of the event type to book (must be active)
             */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Desired start time (ISO 8601, UTC) — must align with a slot boundary
             */
            startTime: string;
            /** @description Guest's display name */
            guestName: string;
            /** @description Optional notes */
            notes?: string;
        };
        /** @description Payload to create a new event type */
        CreateEventTypeRequest: {
            /** @description Display name */
            name: string;
            /** @description Long description */
            description: string;
            /** @description IANA timezone identifier (default: UTC) */
            timezone?: string;
        };
        /** @description Error response body */
        Error: {
            /** @description Machine-readable error code */
            code: string;
            /** @description Human-readable description */
            message: string;
        };
        /** @description Full event type resource returned to the owner */
        EventType: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /** @description Display name */
            name: string;
            /** @description Long description */
            description: string;
            /** @description IANA timezone identifier */
            timezone: string;
            /** @description Whether this event type is visible to guests */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp (ISO 8601, UTC)
             */
            createdAt: string;
        };
        /** @description Response returned to the guest after a successful booking */
        GuestBookingResponse: {
            /**
             * Format: date-time
             * @description Start time (ISO 8601, UTC)
             */
            startTime: string;
            /**
             * Format: date-time
             * @description End time (ISO 8601, UTC)
             */
            endTime: string;
            /** @description Event type name at time of booking */
            eventTypeName: string;
        };
        /** @description Public subset of event type fields shown in guest list */
        PublicEventType: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /** @description Display name */
            name: string;
            /** @description Long description */
            description: string;
            /** @description IANA timezone identifier */
            timezone: string;
        };
        /** @description Computed time slot (not stored) */
        TimeSlot: {
            /**
             * Format: date-time
             * @description Slot start time (ISO 8601, UTC)
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Slot end time (ISO 8601, UTC)
             */
            endTime: string;
            /** @description Whether the slot can be booked */
            available: boolean;
        };
        /** @description Payload to partially update an event type */
        UpdateEventTypeRequest: {
            /** @description Display name */
            name?: string;
            /** @description Long description */
            description?: string;
            /** @description IANA timezone identifier */
            timezone?: string;
            /** @description Whether this event type is active */
            isActive?: boolean;
        };
    };
    responses: never;
    parameters: {
        /** @description Filter by event type ID */
        "OwnerBookingsParams.eventTypeId": string;
        /** @description Filter by start time (inclusive, ISO 8601, UTC) */
        "OwnerBookingsParams.from": string;
        /** @description Maximum number of results (default: 20) */
        "OwnerBookingsParams.limit": number;
        /** @description Number of results to skip (default: 0) */
        "OwnerBookingsParams.offset": number;
        /** @description Filter by start time (inclusive, ISO 8601, UTC) */
        "OwnerBookingsParams.to": string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Guest_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBookingResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Guest_listActiveEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventType"][];
                };
            };
        };
    };
    Guest_getActiveEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Guest_getSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSlot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Owner_listBlackouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blackout"][];
                };
            };
        };
    };
    Owner_createBlackout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlackoutRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blackout"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Owner_deleteBlackout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Owner_listBookings: {
        parameters: {
            query?: {
                /** @description Filter by event type ID */
                eventTypeId?: components["parameters"]["OwnerBookingsParams.eventTypeId"];
                /** @description Filter by start time (inclusive, ISO 8601, UTC) */
                from?: components["parameters"]["OwnerBookingsParams.from"];
                /** @description Filter by start time (inclusive, ISO 8601, UTC) */
                to?: components["parameters"]["OwnerBookingsParams.to"];
                /** @description Maximum number of results (default: 20) */
                limit?: components["parameters"]["OwnerBookingsParams.limit"];
                /** @description Number of results to skip (default: 0) */
                offset?: components["parameters"]["OwnerBookingsParams.offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Owner_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Owner_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Owner_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Owner_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Health_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Health status
                         * @enum {string}
                         */
                        status: "ok";
                    };
                };
            };
        };
    };
}
